Fix UserFormDialog email property error
The error `src/components/UserFormDialog.tsx(66,28): error TS2339: Property 'email' does not exist on type 'UserWithPermissions'.` indicates that the `email` property is being accessed on an object of type `UserWithPermissions` where it is not defined. The code will be updated to correctly access the email property.